### ISSUE TITLE
invalid option "secretName" for volume plugin kubernetes.io/glusterfs

### ISSUE THREAD

**Issue by webwurst** [gluster/gluster-kubernetes#24]
I am trying to create this `PersistantVolumeClaim`:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
```
When doing so this error shows up:
```
kubectl describe persistentvolumeclaim claim1                                                                                           368ms 
Name:		claim1
Namespace:	default
Status:		Pending
Volume:		
Labels:		<none>
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  48m		1m		29	{persistentvolume-controller }			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "slow": glusterfs: invalid option "secretNamespace" for volume plugin kubernetes.io/glusterfs
  49m		7s		170	{persistentvolume-controller }			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "slow": glusterfs: invalid option "secretName" for volume plugin kubernetes.io/glusterfs
```
I set up this `StorageClass` before:
```yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi.gluster.svc:8080"
  # restuser: "admin"
  secretNamespace: "gluster"
  secretName: "heketi-secret"
```
