### ISSUE TITLE
Issues with dynamic volume provisioning on Kubernetes 1.5

### ISSUE THREAD

**Issue by nielspardon** [gluster/gluster-kubernetes#274]
I have deployed heketi via gluster-kubernetes on my Kubernetes 1.5.4 cluster which worked fine until I created a persistent volume claim which got stuck in pending.

After looking into the log of the pvc I noticed that it comlained about an invalid parameter `endpoint` which lead me to issue #87. So I removed the `endpoint` parameter, recreated the storage class but now I'm getting:

```
Failed to provision volume with StorageClass "gluster-heketi": glusterfs: create volume err: failed to create endpoint/service <nil>.
```

So I dug a bit deeper. I recognized that there was an issue creating the `clusterrolebinding` via `kubectl` since there's no CLI for it in Kubernetes 1.5 as it seems. So I tried to create the `clusterrolebinding` from file (not sure whether I did the right thing). Unfortunately that didn't work.

There should be an updated example for the StorageClass yaml (without `endpoint`).

Can you help me to further debug this? What else can I check?

**Comment by jarrpa** [comment]
Can you paste what you did to create the `clusterrolebinding`? For some troubleshooting, you can try doing various `oc` commands using the `--as` option to see what operations the SA has access to, e.g. `oc --as=system:serviceaccount:<namespace>:heketi-service-account get nodes`, and see if it can create endpoints.

**Comment by nielspardon** [comment]
Here's the content of my clusterrolebinding.yml I used:

```yaml
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: heketi-sa-view
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: heketi-service-account
    namespace: default
```

I simply ran `kubectl create -f clusterrolebinding.yml` with this.

In order to test the service account I tried the following with a service definition which worked:
```
kubectl --as=system:serviceaccount:default:heketi-service-account create -f heketi-svc.yaml
```

**Comment by jarrpa** [comment]
Wait... thinking about it, that should have nothing to do with this. The GlusterFS provisioner should be handling that, not heketi. Calling in @humblec on this one.

**Comment by nielspardon** [comment]
So reading about the GlusterFS StorageClass in the Kubernetes documentation I created the StorageClass with this yaml:

```yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.112.165:8080"
```

The examples had restuser & restuserkey parameters which I dropped since according to the example authentication [isn't configured anyway](https://github.com/gluster/gluster-kubernetes/blob/master/docs/examples/hello_world/README.md#create-a-storageclass-for-our-glusterfs-dynamic-provisioner) and the Kubernetes GlusterFS documentation said [it would try to authenticate if those parameters were set.](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#glusterfs)

**Comment by nielspardon** [comment]
My pvc yaml then looks like this:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster1
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
```
