### ISSUE TITLE
GlusterFS cant mount volume at container creation

### ISSUE THREAD

**Issue by felixPG** [gluster/gluster-kubernetes#334]
[nginx-pod-glusterfs.log.txt](https://github.com/gluster/gluster-kubernetes/files/1266807/nginx-pod-glusterfs.log.txt)
Hi:

I habe a glusterfs running inside kubernetes, PV and PVC created withour problems but pods are unable to mount the volumes that  I want:

Here my config files:

StorageClass and Claim:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://s-smartc2-zprei:30625"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster1
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
       storage: 1Gi
```
Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: gcr.io/google_containers/nginx-slim:0.8
    ports:
    - name: web
      containerPort: 80
    securityContext:
      privileged: true
    volumeMounts:
    - name: gluster-vol1
      mountPath: /usr/share/nginx/html
  volumes:
  - name: gluster-vol1
    persistentVolumeClaim:
      claimName: gluster1
```

Pods are in ContainerCreating status forever, here the logs of the pod:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pods
NAME                     READY     STATUS              RESTARTS   AGE
glusterfs-72rcn          1/1       Running             0          1h
glusterfs-hfvrd          1/1       Running             1          1h
glusterfs-msqlp          1/1       Running             0          1h
heketi-730120522-d36p6   1/1       Running             0          1h
nginx-pod                0/1       ContainerCreating   0          4m
```
Pod Logs:
```
  3m    3m      1       kubelet, s-smartc4-zprei                **Warning FailedMount**     MountVolume.SetUp failed for volume "pvc-89998771-8e37-11e7-9fa1-005056b77c78" : glusterfs: mount failed: mount failed: exit status 1
Mounting command: mount
Mounting arguments: 192.168.133.4:**vol_cd634264e40aa5a24bc21d8b73c3c787** /var/lib/kubelet/pods/9985b31a-8e37-11e7-9fa1-005056b77c78/volumes/kubernetes.io~glusterfs/pvc-89998771-8e37-11e7-9fa1-005056b77c78 glusterfs [auto_unmount log-level=ERROR log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-89998771-8e37-11e7-9fa1-005056b77c78/nginx-pod-glusterfs.log backup-volfile-servers=192.168.133.2:192.168.133.3:192.168.133.4]
**Output: /usr/bin/fusermount-glusterfs: mount failed: Invalid argument**
Mount failed. Please check the log file for more details.

 the following error information was pulled from the glusterfs log to help diagnose this issue:
[2017-08-31 10:34:00.548499] I [client.c:2294:notify] 0-vol_cd634264e40aa5a24bc21d8b73c3c787-client-0: parent translators are ready, attempting connect on transport
[2017-08-31 10:34:00.550338] I [client.c:2294:notify] 0-vol_cd634264e40aa5a24bc21d8b73c3c787-client-1: parent translators are ready, attempting connect on transport
```

PV and PVC details:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM              STORAGECLASS     REASON    AGE
pvc-89998771-8e37-11e7-9fa1-005056b77c78   1Gi        RWO           Delete          **Bound**     default/gluster1   gluster-heketi             6m
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl get pvc
NAME       STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS     AGE
gluster1   **Bound**     pvc-89998771-8e37-11e7-9fa1-005056b77c78   1Gi        RWO           gluster-heketi   6m
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
Glusterfs connectivity test:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# curl s-smartc2-zprei:30625/hello
Hello from Heketiroot@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
Volume info FROM glusterfs pod:
```
[root@s-smartc4-zprei /]# gluster volume info vol_cd634264e40aa5a24bc21d8b73c3c787

Volume Name: vol_cd634264e40aa5a24bc21d8b73c3c787
Type: Replicate
Volume ID: f895aa2d-d60c-4343-ad9a-b7a2a9bd1934
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: 192.168.133.4:/var/lib/heketi/mounts/vg_acdc18362c9aa66cdcbf400c59c2cea1/brick_f4a87ef6fdd1cb0af420dff3da64a213/brick
Brick2: 192.168.133.3:/var/lib/heketi/mounts/vg_c7217dce005502fd5a2bc9eb775809b8/brick_15bdd5f4baa6aac305b92dea8a47d5e4/brick
Brick3: 192.168.133.2:/var/lib/heketi/mounts/vg_4c0de25e23a85bb1c2d47c5883be84db/brick_6e9e7dfdcd25a24618efe62193b0eb26/brick
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
```
Node Pod provisioned:
```
root@s-smartc2-zprei:/opt/kubernetes/glusterfs# kubectl describe pod nginx-pod |grep Node
Node:           s-smartc4-zprei/192.168.133.4
Node-Selectors: <none>
root@s-smartc2-zprei:/opt/kubernetes/glusterfs#
```
Attached the log from the node where the pod was provisioned.

Could anyone sayme waht happend with the moun command???? 

Thanks
