### ISSUE TITLE
PVC is stuck at PENDING

### ISSUE THREAD

**Issue by Justluckyg** [gluster/gluster-kubernetes#367]
Hello..

I currently have a glusterfs deployment that I was able to test using the nginx helloworld app and it appears to be getting the data. however our db deployments is in a separate namespace. is that the reason why am i getting these?
```
Name:       maindb-1-data-maindb-1-0
Namespace:  myNamespace
StorageClass:   gluster-default
Status:     Pending
Volume:
Labels:     app=maindb-1
        database-name=maindb
        maindb-mongodb-access=true
Annotations:    volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Capacity:
Access Modes:
Events:
  FirstSeen LastSeen    Count   From                SubObjectPath   Type        Reason          Message
  --------- --------    -----   ----                -------------   --------    ------          -------
  1h        22s     144 persistentvolume-controller         Warning     ProvisioningFailed  Failed to provision volume with StorageClass "gluster-default": glusterfs: create volume err: error creating volume Failed to get list of pods
```

**Comment by jarrpa** [comment]
@Justluckyg What was the procedure you followed that allowed you to provision a GlusterFS volume?

**Comment by Justluckyg** [comment]
@jarrpa the successful one was followed line by line through [here](https://github.com/gluster/gluster-kubernetes/blob/master/docs/examples/hello_world/README.md)

To test it in our environment, we basically a tool that we used for kops in provisioning kubernetes cluster in AWS, this is my first time using that tool in a bare metal. This tool allows me to automate the creation of a statefulset. When using it with KOPS, it uses the EBS volumes automatically for PVC. In order to point it to GlusterFS volume, I created this storageClass.

```
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.233.42.124:8080"
  restuser: "joe"
  restuserkey: "My Secret Life"
```

Now our databases launches in a totally different namespace that we deployed. Heketi and Gfs uses default. Not sure if that's the problem or I'm probably just missing some steps.

And this is our replicaset yaml file:
```
## Sentinel Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: #{{my_name}}
  namespace: lenddo
data:
  #{{name}}.conf: |
    net:
      port: #{{port}}
    replication:
      replSetName: #{{replicaset}}
    storage:
      dbPath: /data
      journal:
        enabled: true
      engine: wiredTiger
      wiredTiger:
        engineConfig:
          cacheSizeGB: #{{ram}}
---
apiVersion: v1
kind: Service
metadata:
  name: #{{my_name}}
  namespace: lenddo
  labels:
    app: #{{my_name}}
spec:
  clusterIP: None
  ports:
  - port:  #{{port}}
    protocol: TCP
    name: #{{my_name}}
  - port: 9001
    protocol: TCP
    name: #{{my_name}}-exp
  selector:
    app: #{{my_name}}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: #{{my_name}}
  namespace: lenddo
spec:
  serviceName: #{{my_name}}
  template:
    metadata:
      labels:
        app: #{{my_name}}
        database-name: #{{name}}
        #{{name}}-mongodb-access: "true"
    spec:
      containers:
      - name: #{{my_name}}
        image: mongo:3.4
        ports:
        - name: #{{my_name}}
          protocol: TCP
          containerPort: #{{port}}
        volumeMounts:
          - name: #{{my_name}}-data
            mountPath: /data
          - name: #{{my_name}}-journal
            mountPath: /data/journal
          - name: #{{name}}-config
            mountPath: /mongodb/
        command:
          - mongod
          - --config
          - /mongodb/#{{name}}.conf
        resources:
          requests:
            cpu: #{{cpus}}
            memory: #{{ram}}Gi
      - name: #{{name}}-#{{number}}-mongodb-exporter
        image: lowstz/mongodb-exporter
        ports:
        - name: #{{name}}-#{{number}}-exp
          protocol: TCP
          containerPort: 9001
        args:
        - --mongodb.uri
        - #{{port}}
      nodeSelector:
        #{{#is_database}}
        databases: "true"
        #{{/is_database}}
        #{{#is_arbiter}}
        arbiters: "true"
        #{{/is_arbiter}}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: database-name
                  operator: In
                  values:
                  - #{{name}}
                  - socialdb # all instances should prefer to not be scheduled on a socialdb node @todo: Find a better way to do this
              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: #{{name}}-config
        configMap:
          name: #{{my_name}}
          items:
            - key: #{{name}}.conf
              path: #{{name}}.conf
  volumeClaimTemplates:
  - metadata:
      name: #{{my_name}}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: #{{size}}Gi
  - metadata:
      name: #{{my_name}}-journal
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
