### ISSUE TITLE
Create distributed-replicated volume in storageclass

### ISSUE THREAD

**Issue by es1o** [gluster/gluster-kubernetes#473]
Hi, I use heketi to create dynamic glusterfs volumes.
I created storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
parameters:
  resturl: http://heketi-storage-glusterfs.cluster.local
  restuser: admin
  secretName: heketi-storage-admin-secret
  secretNamespace: glusterfs
  volumetype: replicate:2
provisioner: kubernetes.io/glusterfs
metadata:
  name: glusterfs-storage-replica-2
```
I don't know how to create distributed replicated volume with 2 replicas and 2 distributed parts. In documentation I found only how to create replica, distributed volume and disperse volume.
Is it possible to create 2x2 volume dynamically?
