### ISSUE TITLE
storageClassName support in PVC

### ISSUE THREAD

**Issue by sekrett** [gluster/gluster-kubernetes#520]
Documentation says I should create a PVC this way:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: my-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
```

It works but there are many helm chart which generate a PVC in a different way:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gluster-heketi
```

And this PVC will fail to create. Maybe specifying annotations is an old way and `storageClassName` support should be added now for convenience?
