### ISSUE TITLE
Unable to provision Volume using Heketi with 1 only node on GlusterFS

### ISSUE THREAD

**Issue by devilmind81** [gluster/gluster-kubernetes#540]
Hi all,
I have exattly the same issue described here #454 but all suggestion is not fixing my issue.
I have been setup glusterfs on one node in a dev environment and I'm trying to add a StorageClass in the openshift in order to manage the volume creation on it.

This is my  StorageClass yaml file content:

```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.10.10.10:8080"
  restuser: "admin"
  restuserkey: "admin"
  **volumetype: "replicate:1"**
```

and this is my pvc yaml file content:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: heketi-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 4Gi
```

but when I create a pvc I'm obtaining:

```
Name:          heketi-pvc
Namespace:     test
StorageClass:  heketi
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=heketi
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  3s    persistentvolume-controller  Failed to provision volume with StorageClass "heketi": create volume error: error creating volume Failed to allocate new volume: No space

```
in the heketi logs I see:
```

Nov 27 17:39:58 ocpglusterfs-0 heketi[14686]: [heketi] ERROR 2018/11/27 17:39:58 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:37: Minimum brick size limit reached.  Out of space.
Nov 27 17:39:58 ocpglusterfs-0 heketi[14686]: [heketi] ERROR 2018/11/27 17:39:58 /src/github.com/heketi/heketi/apps/glusterfs/operations.go:1167: Create Volume Build Failed: No space
```

I see that the follow topology has something that sounds no good for me, the Free (Gib):

```
Cluster Id: 913b61c4b6429e56550cfb4958f4a63c

    File:  true
    Block: true

    Volumes:

    Nodes:

        Node Id: b374dccf5b3ae3ea2576a9705e12cada
        State: online
        Cluster Id: 913b61c4b6429e56550cfb4958f4a63c
        Zone: 1
        Management Hostnames: 10.10.10.10
        Storage Hostnames: 10.10.10.10
        Devices:
                Id:3dd5b7772a685f538696c56359665b6f   Name:/dev/sdb            State:online    Size (GiB):49      Used (GiB):49      Free (GiB):0

```

The glusterfs and heketi were installed from scratch, why hasn't available space?

Can someone help me here? I'm stuck and I don't know how to proceed.
Thanks in advance.

PS:
I read the documentation at link:
https://kubernetes.io/docs/concepts/storage/storage-classes/#glusterfs
and I have tried also with  ` **volumetype: "none"**` but the same issue occurs.
