### ISSUE TITLE
Can glusterfs be installed on a single machine?

### ISSUE THREAD

**Issue by booboothefool** [gluster/gluster-kubernetes#563]
- https://github.com/IBM/charts/tree/master/stable/ibm-glusterfs
- https://www.ibm.com/support/knowledgecenter/SSBS6K_3.1.2/manage_cluster/configure_glusterfs_during.html

Have been trying to use the following:
```
storage-glusterfs:
  nodes:
    - ip: 169.xx.xx.xx
      devices:
         - /dev/disk/gluster-disk-1
#      devices:
#        - /dev/disk/gluster-disk-1
#        - <link path>/<symlink of device bbb>
#    - ip: <storage_node_n_IP_address>
#      devices:
#        - <link path>/<symlink of device ccc>
#    - ip: <storage_node_o_IP_address>
#      devices:
#        - <link path>/<symlink of device ddd>
  storageClass:
    create: true
    name: glusterfs
    isDefault: true
    volumeType: replicate:1
```

However when trying to claim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: glusterfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

It fails saying "requires more than 1 replica".

I'd like to try out a one machine/one node setup for learning/evaluation purposes.
