### ISSUE TITLE
Set up Heketi Rest URL in Storage Class

### ISSUE THREAD

**Issue by BostjanBozic** [gluster/gluster-kubernetes#570]
Hello,

Foremost I am sorry that I am setting this up as as issue, it is very likely that there I am doing something wrong on my part.

- Kubernetes version: v1.13.1
- Gluster version: 6.0

What I did was I deployed Heketi on Kubernetes and set up topology to use external servers for volume provisioning.
From Heketi side, everything is working as intended - service is up and running, devices are created.

I have set up Heketi service, as I plan to use it for `StorageClass`:
```
apiVersion: v1
kind: Service
metadata:
  name: heketi
  namespace: kube-system
  labels:
    glusterfs: heketi-service
    heketi: service
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    glusterfs: heketi-pod
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080
```

And I have created `StorageClass` with following configuration:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: heketi
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: http://10.109.154.186:8080
  restuser: "admin_from_secrets"
  restuserkey: "password_from_secrets"
```

Currently as you can see, resturl is hard coded IP. What I want to do is actually use service created above.
I have tried multiple adresses, e.g. `heketi.kube-system.svc.cluster.local`, but I always receive following error when creating PVC:

> Failed to provision volume with StorageClass "heketi": failed to create volume: failed to create volume: Post http://heketi.kube-system.svc.cluster.local:8080/volumes: dial tcp: lookup heketi.kube-system.svc.cluster.local on 10.1.50.10:53: no such host

Any kind of suggestion what I am doing wrong would be great.

Thank you and best regards,
Bostjan
