### ISSUE TITLE
no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by freeeflyer** [gluster/gluster-kubernetes#627]
gk-deploy outputs the message : 
```
Deploying GlusterFS pods.
sed -e 's/storagenode\: glusterfs/storagenode\: 'glusterfs'/g' /root/kube/gluster-kubernetes/deploy/kube-templates/glusterfs-daemonset.yaml | /usr/bin/kubectl -n gk create -f - 2>&1
error: unable to recognize "STDIN": no matches for kind "DaemonSet" in version "extensions/v1beta1"
Waiting for GlusterFS pods to start ...
Checking status of pods matching '--selector=glusterfs=pod':
```
It seems that for v1.16+ we should use extensions/v1 and no more v1beta
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

**Comment by sesopenko** [comment]
According to the latest documentation for kubernetes 1.17 we'd use `apps/v1` and not `extensions/v1`.  See documentation entries for [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/), [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)

**Comment by freeeflyer** [comment]
I patched my version, this part seems to work.
If I understand correctly, there is still a problem with travis-ci that prevent from merging the patch ?

**Comment by MED-SALAH** [comment]
I am using kubctl 1.18 and i try to execute this command, but i have this error. 
HOW I CAN FIX THAT PLEASE !!!!!!!!!!!!!!!!!

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml

ERRORS : 
no matches for kind "DaemonSet" in version "extensions/v1beta1"

**Comment by danielnbalasoiu** [comment]
Support for extensions/v1beta1 was removed in v1.16.
Try replacing `extensions/v1beta1` with `apps/v1`

```
k api-resources | grep -i daemon
daemonsets                        ds           apps                           true         DaemonSet
```

**Comment by rlpatrao** [comment]
I encountered the same thing and resolved it by : 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"

```

notes:
1. changed apiVersion to  "apps/v1"
2. added selector
  ```
selector:
    matchLabels:
      k8s-app: fluentd-logging
```
3. made sure that matchLabels selectors (e.g. k8s-app) name should match in spec and template.
`k8s-app: fluentd-logging`
